name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: SampleCICD
      run: xcodebuild build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
    - name: Test testplan  
      run: xcodebuild test -scheme SampleCICD -destination 'platform:iOS Simulator, id:40398680-8AE9-4D4C-BFB7-8190F275F50C, OS:14.4, name:iPhone 11' -testPlan SampleCICDUnitTest
