name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
    - name: Test testplan  
      run: xcodebuild test -scheme SampleCICD -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11' -testPlan SampleCICDUnitTest
