name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Test testplan 
      working-directory: SampleCICD
      run: xcodebuild test -scheme SampleCICD -destination 'platform=iOS Simulator,OS=14.4,name=iPhone X' -testPlan SampleCICDUnitTest 

